language: php

php:
  - 7.1
  - 7.2

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit --coverage-text
  - vendor/bin/coke

matrix:
  fast_finish: true
